version: '3.16'

# services:
#   nginx:
#     build:
#       context: ./Nginx
#       dockerfile: Dockerfile
#     container_name: nginx
#     ports:
#       - "80:80"
#     networks:
#       - internal
