FROM debian:12.7-slim

RUN apt update -y && apt upgrade -y && apt install -y php-fpm php-mysqli curl
COPY ./conf/www.conf /etc/php/8.2/fpm/pool.d/.
COPY ./tools/entrypoint.sh .
RUN chmod +x entrypoint.sh
ENTRYPOINT [ "./entrypoint.sh" ]