FROM Debian:12.6-slim

# RUN apt-get update -y && apt-get upgrade -y && apt-get install -y nginx vim sudo

# RUN mkdir /etc/run

# COPY ./script/entrypoint.sh /etc/run

# WORKDIR /etc/run
# ENTRYPOINT [ "bash", "entrypoint.sh" ]
