FROM debian:12.7-slim

RUN apt update -y && apt upgrade -y && apt install -y mariadb-server
COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY ./tools/init.sql /etc/mysql/init.sql

RUN mkdir /run/mysqld

CMD [ "mysqld" ]