FROM debian:12.7-slim

RUN apt update -y && apt upgrade -y && apt install -y nginx \
    openssl \
    && mkdir -p /etc/nginx/ssl \
    && mkdir -p /run/nginx && \
    chown -R www-data /var/lib/nginx

COPY ./conf/default /etc/nginx/sites-available/.
COPY ./conf/default /etc/nginx/nginx.conf
COPY ./tools/entrypoint.sh .

RUN chmod +x entrypoint.sh

CMD [ "./entrypoint.sh" ]