services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: dockerfile
    container_name: mariadb
    networks:
      - internal
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./.env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    container_name: wordpress
    networks:
      - internal
    depends_on:
      - mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - internal
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ./.env
    restart: on-failure

networks:
  internal:
    driver: bridge

volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/ebmarque/data/html
      o: bind
  mariadb:
    driver_opts:
      type: none
      device: /home/ebmarque/data/mysql
      o: bind