FROM debian:latest

RUN apt update -y && apt upgrade -y && apt install -y php-fpm php-mysqli curl
COPY www.conf /etc/php/8.2/fpm/pool.d/.
COPY entrypoint.sh .
RUN chmod 777 entrypoint.sh
ENTRYPOINT [ "./entrypoint.sh" ]